version: "3.9"

services:
  backend:
    build: ./backend
    container_name: tracker-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: tracker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
